# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cluster": "00_Node_cluster.ipynb",
         "cluster_node": "00_Node_cluster.ipynb",
         "tree_clusters": "01_tree_clusters.ipynb",
         "inside_polygon": "00_Node_cluster.ipynb",
         "poligon_non_convex_from_Points": "00_Node_cluster.ipynb",
         "poligon_non_convex_random_gen": "00_Node_cluster.ipynb",
         "module_path": "02_Clustering.ipynb",
         "clustering": "02_Clustering.ipynb",
         "recursive_clustering": "02_Clustering.ipynb",
         "compute_dbscan": "02_Clustering.ipynb",
         "auto_knee_average": "02_Clustering.ipynb",
         "compute_hdbscan": "02_Clustering.ipynb",
         "compute_OPTICS": "02_Clustering.ipynb",
         "compute_Natural_cities": "02_Clustering.ipynb"}

modules = ["Node_cluster.py",
           "Tree_clusters.py",
           "Clustering.py"]

doc_url = "https://CentroGeo.github.io/HierarchicalGeoClustering/"

git_url = "https://github.com/CentroGeo/HierarchicalGeoClustering/tree/master/"

def custom_doc_links(name): return None
