# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cluster": "00_Node_cluster.ipynb"}

modules = ["core.py"]

doc_url = "https://CentroGeo.github.io/HierarchicalGeoClustering/"

git_url = "https://github.com/CentroGeo/HierarchicalGeoClustering/tree/master/"

def custom_doc_links(name): return None
