# AUTOGENERATED! DO NOT EDIT! File to edit: src/02_Clustering.ipynb (unless otherwise specified).

__all__ = ['module_path']

# Cell
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from .Tree_clusters import cluster_node