# AUTOGENERATED! DO NOT EDIT! File to edit: 00_Node_cluster.ipynb (unless otherwise specified).

__all__ = ['cluster']

# Cell
class cluster(object):
    polygon_cluster = None
    point_cluster_noise = None

    def __init__(self):
        self.polygon_cluster = None
        self.density = None
        self.point_cluster_noise = None
