name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with: 
          python-version: 3.11
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Install Nbdev Dependencies and package dependencies
        shell: bash -el {0}
        run: |
          
          mamba install nbdev
          mamba install cgal
          mamba install matplotlib
          mamba install setuptools
          mamba install scikit-learn
          mamba install pandas
          mamba install anytree
          mamba install shapely
          mamba install geopandas
          mamba install kneed
          mamba install graph-tool
          
          nbdev_docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_docs
          # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

