name: Test CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with: 
          python-version: 3.11
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Install Nbdev Dependencies 
        shell: bash -el {0}
        run: |
          mamba install pip
          pip install -Uq git+https://github.com/fastai/ghapi.git # you need this for enablin>
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -U git+https://github.com/fastai/nbdev.git

          mamba install cgal
          mamba install matplotlib
          mamba install setuptools
          mamba install scikit-learn
          mamba install pandas
          mamba install anytree
          mamba install shapely
          mamba install geopandas
          mamba install kneed
          mamba install graph-tool
          mamba install hdbscan
          pip install -U nbdev
          echo $(nbdev_bump_version)
          
          
      - name: Test the package
        shell: bash -l {0}
        run: | 
        
          if [[ `git status --porcelain -uno` ]]; then
            git status -uno
            echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
            echo -e "This error can also happen if you are using an older version of nbdev relative to what is in CI.  Please try to upgrade nbdev with the command `pip install -U nbdev`"
            false
          fi
          nbdev_export
          if [[ `git status --porcelain -uno` ]]; then
            echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
            git status -uno
            git diff
            exit 1;
          fi
          if [ ! $SKIP_TEST ]; then
            nbdev_test --flags "$FLAGS"
          fi